insert into genre (id, name, parent_id, slug) values (1, 'Fiction', null, 'genre-syr-842');
insert into genre (id, name, parent_id, slug) values (2, 'Nonfiction', null, 'genre-vsf-086');
insert into genre (id, name, parent_id, slug) values (3, 'Poetry', null, 'genre-zqf-671');
insert into genre (id, name, parent_id, slug) values (4, 'Drama', null, 'genre-jvz-481');
insert into genre (id, name, parent_id, slug) values (5, 'Comedy', 4, 'genre-vzz-588');
insert into genre (id, name, parent_id, slug) values (6, 'Tragedy', 4, 'genre-aux-854');
insert into genre (id, name, parent_id, slug) values (7, 'Fantasy', 1, 'genre-wlv-703');
insert into genre (id, name, parent_id, slug) values (8, 'Traditional', 1, 'genre-sxa-518');
insert into genre (id, name, parent_id, slug) values (9, 'Historical', 1, 'genre-ioo-195');
insert into genre (id, name, parent_id, slug) values (10, 'Mystery', 1, 'genre-nbv-421');
insert into genre (id, name, parent_id, slug) values (11, 'Realistic Fiction', 1, 'genre-bdc-875');
insert into genre (id, name, parent_id, slug) values (12, 'Science Fiction', 1, 'genre-acf-071');
insert into genre (id, name, parent_id, slug) values (13, 'Romance', 1, 'genre-oaf-452');
insert into genre (id, name, parent_id, slug) values (14, 'Thriller', 1, 'genre-mar-783');
insert into genre (id, name, parent_id, slug) values (15, 'Biography', 2, 'genre-wyj-390');
insert into genre (id, name, parent_id, slug) values (16, 'Autobiography', 2, 'genre-myh-594');
insert into genre (id, name, parent_id, slug) values (17, 'Narrative', 2, 'genre-jwf-544');
insert into genre (id, name, parent_id, slug) values (18, 'Periodicals', 2, 'genre-gwm-495');
insert into genre (id, name, parent_id, slug) values (19, 'Reference', 2, 'genre-gwy-027');
insert into genre (id, name, parent_id, slug) values (20, 'Lyric', 3, 'genre-xic-301');
insert into genre (id, name, parent_id, slug) values (21, 'Narrative', 3, 'genre-ljq-890');
insert into genre (id, name, parent_id, slug) values (22, 'Dramatic', 3, 'genre-eun-497');
insert into genre (id, name, parent_id, slug) values (23, 'Mystery', 11, 'genre-yvk-455');
insert into genre (id, name, parent_id, slug) values (24, 'Myth', 8, 'genre-zgg-650');
insert into genre (id, name, parent_id, slug) values (25, 'Legend', 8, 'genre-zzc-207');
insert into genre (id, name, parent_id, slug) values (26, 'Folktale', 8, 'genre-zeb-204');
insert into genre (id, name, parent_id, slug) values (27, 'Tall Tale', 8, 'genre-pgi-957');
insert into genre (id, name, parent_id, slug) values (28, 'Fairy Tale', 8, 'genre-zos-205');
insert into genre (id, name, parent_id, slug) values (29, 'Fable', 8, 'genre-wgm-204');
insert into genre (id, name, parent_id, slug) values (30, 'Memoir', 16, 'genre-lux-719');
-- insert into genre (id, name, parent_id, slug) values (31, 'Comedy|Drama|Fantasy|Mystery|Romance', 39, 'genre-yek-306');
-- insert into genre (id, name, parent_id, slug) values (32, 'Drama|Fantasy|Romance', 11, 'genre-aro-609');
-- insert into genre (id, name, parent_id, slug) values (33, 'Adventure|Children|Comedy|Drama', 60, 'genre-gyl-322');
-- insert into genre (id, name, parent_id, slug) values (34, 'Drama', 19, 'genre-jur-858');
-- insert into genre (id, name, parent_id, slug) values (35, 'Documentary', 25, 'genre-rrb-918');
-- insert into genre (id, name, parent_id, slug) values (36, 'Documentary', 51, 'genre-hjy-911');
-- insert into genre (id, name, parent_id, slug) values (37, 'Action|Adventure|Comedy', 59, 'genre-ekk-292');
-- insert into genre (id, name, parent_id, slug) values (38, 'Comedy|Drama', 21, 'genre-fdk-410');
-- insert into genre (id, name, parent_id, slug) values (39, 'Drama|War', 10, 'genre-kaq-245');
-- insert into genre (id, name, parent_id, slug) values (40, 'Drama|Romance', 48, 'genre-gwx-273');
-- insert into genre (id, name, parent_id, slug) values (41, 'Drama', 13, 'genre-yeu-006');
-- insert into genre (id, name, parent_id, slug) values (42, 'Action', 94, 'genre-jcm-304');
-- insert into genre (id, name, parent_id, slug) values (43, 'Crime|Drama|Romance', 70, 'genre-dov-756');
-- insert into genre (id, name, parent_id, slug) values (44, 'Drama', 74, 'genre-noi-516');
-- insert into genre (id, name, parent_id, slug) values (45, 'Animation|Horror', 38, 'genre-dox-194');
-- insert into genre (id, name, parent_id, slug) values (46, 'Action|Animation|Mystery|Sci-Fi', 64, 'genre-hvy-912');
-- insert into genre (id, name, parent_id, slug) values (47, 'Horror', 81, 'genre-ctu-645');
-- insert into genre (id, name, parent_id, slug) values (48, 'Horror', 100, 'genre-ebm-883');
-- insert into genre (id, name, parent_id, slug) values (49, 'Documentary|IMAX', 89, 'genre-avs-108');
-- insert into genre (id, name, parent_id, slug) values (50, 'Drama', 13, 'genre-cqe-310');
-- insert into genre (id, name, parent_id, slug) values (51, 'Comedy|Drama', 98, 'genre-nau-798');
-- insert into genre (id, name, parent_id, slug) values (52, 'Action|Adventure|Comedy', 47, 'genre-mnx-948');
-- insert into genre (id, name, parent_id, slug) values (53, 'Children|Comedy', 79, 'genre-zwn-335');
-- insert into genre (id, name, parent_id, slug) values (54, 'Documentary', 58, 'genre-hxq-174');
-- insert into genre (id, name, parent_id, slug) values (55, 'Drama|Romance', 95, 'genre-siv-791');
-- insert into genre (id, name, parent_id, slug) values (56, 'Drama', 39, 'genre-fcu-384');
-- insert into genre (id, name, parent_id, slug) values (57, 'Fantasy|Horror|Mystery|Romance', 69, 'genre-wmr-021');
-- insert into genre (id, name, parent_id, slug) values (58, 'Drama|Mystery', 79, 'genre-zyq-045');
-- insert into genre (id, name, parent_id, slug) values (59, 'Action|Crime|Thriller', 95, 'genre-bjf-798');
-- insert into genre (id, name, parent_id, slug) values (60, 'Crime|Drama', 85, 'genre-yyk-376');
-- insert into genre (id, name, parent_id, slug) values (61, 'Documentary', 98, 'genre-rxi-870');
-- insert into genre (id, name, parent_id, slug) values (62, 'Adventure|Comedy|Fantasy|Musical|Romance', 9, 'genre-hdk-774');
-- insert into genre (id, name, parent_id, slug) values (63, 'Action|Adventure|Crime|Thriller', 7, 'genre-egy-287');
-- insert into genre (id, name, parent_id, slug) values (64, 'Adventure|Fantasy|IMAX', 44, 'genre-aca-722');
-- insert into genre (id, name, parent_id, slug) values (65, 'Drama', 10, 'genre-atv-834');
-- insert into genre (id, name, parent_id, slug) values (66, 'Comedy', 40, 'genre-xgi-357');
-- insert into genre (id, name, parent_id, slug) values (67, 'Drama|War', 1, 'genre-lkb-838');
-- insert into genre (id, name, parent_id, slug) values (68, 'Comedy', 11, 'genre-kxf-506');
-- insert into genre (id, name, parent_id, slug) values (69, 'Thriller', 87, 'genre-ukq-182');
-- insert into genre (id, name, parent_id, slug) values (70, 'Crime|Drama|Thriller', 20, 'genre-qfk-591');
-- insert into genre (id, name, parent_id, slug) values (71, 'Comedy|Crime|Drama|Mystery|Thriller', 5, 'genre-bgu-461');
-- insert into genre (id, name, parent_id, slug) values (72, 'Horror|Thriller', 19, 'genre-whz-057');
-- insert into genre (id, name, parent_id, slug) values (73, 'Drama', 66, 'genre-wvx-234');
-- insert into genre (id, name, parent_id, slug) values (74, 'Horror|Thriller', 35, 'genre-nau-083');
-- insert into genre (id, name, parent_id, slug) values (75, 'Adventure|Drama', 11, 'genre-zmv-752');
-- insert into genre (id, name, parent_id, slug) values (76, 'Documentary', 90, 'genre-eux-065');
-- insert into genre (id, name, parent_id, slug) values (77, 'Action|Drama|Thriller', 51, 'genre-xrh-601');
-- insert into genre (id, name, parent_id, slug) values (78, 'Animation', 2, 'genre-uar-546');
-- insert into genre (id, name, parent_id, slug) values (79, 'Documentary', 9, 'genre-vep-515');
-- insert into genre (id, name, parent_id, slug) values (80, 'Documentary', 26, 'genre-hiq-245');
-- insert into genre (id, name, parent_id, slug) values (81, 'Action|Adventure|Animation|Fantasy|Sci-Fi', 12, 'genre-xbv-697');
-- insert into genre (id, name, parent_id, slug) values (82, 'Action|Adventure|Drama|Romance|War', 9, 'genre-agv-754');
-- insert into genre (id, name, parent_id, slug) values (83, 'Drama', 77, 'genre-cgy-127');
-- insert into genre (id, name, parent_id, slug) values (84, 'Action|Adventure|Comedy', 26, 'genre-acq-077');
-- insert into genre (id, name, parent_id, slug) values (85, 'Documentary', 86, 'genre-isx-964');
-- insert into genre (id, name, parent_id, slug) values (86, 'Adventure|Drama|Romance', 59, 'genre-dbk-912');
-- insert into genre (id, name, parent_id, slug) values (87, 'Drama', 72, 'genre-own-951');
-- insert into genre (id, name, parent_id, slug) values (88, 'Crime|Drama|Mystery', 82, 'genre-nrf-759');
-- insert into genre (id, name, parent_id, slug) values (89, 'Drama', 90, 'genre-mko-837');
-- insert into genre (id, name, parent_id, slug) values (90, 'Comedy|Romance', 81, 'genre-kuj-417');
-- insert into genre (id, name, parent_id, slug) values (91, 'Drama', 25, 'genre-hol-320');
-- insert into genre (id, name, parent_id, slug) values (92, 'Comedy|Crime|Drama|Mystery|Thriller', 82, 'genre-wxh-026');
-- insert into genre (id, name, parent_id, slug) values (93, 'Adventure|Animation|Children', 11, 'genre-cdd-353');
-- insert into genre (id, name, parent_id, slug) values (94, 'Crime|Drama', 31, 'genre-nhk-898');
-- insert into genre (id, name, parent_id, slug) values (95, 'Adventure|Musical', 95, 'genre-ybu-033');
-- insert into genre (id, name, parent_id, slug) values (96, 'Comedy', 57, 'genre-sjv-853');
-- insert into genre (id, name, parent_id, slug) values (97, 'Film-Noir|Thriller|War', 1, 'genre-cfx-474');
-- insert into genre (id, name, parent_id, slug) values (98, 'Drama|Horror|Mystery|Thriller', 88, 'genre-qmb-595');
-- insert into genre (id, name, parent_id, slug) values (99, 'Documentary', 100, 'genre-rxo-480');
-- insert into genre (id, name, parent_id, slug) values (100, 'Animation|Comedy|Drama', 90, 'genre-mrt-353');
