insert into tag (id, name, slug) values (1, 'ut erat curabitur', 'tag-yiv-047');
insert into tag (id, name, slug) values (2, 'purus sit amet ', 'tag-hgq-801');
insert into tag (id, name, slug) values (3, 'nibh in  aliquam', 'tag-xic-038');
insert into tag (id, name, slug) values (4, 'libero ', 'tag-xmw-568');
insert into tag (id, name, slug) values (5, 'amet  libero quis', 'tag-kep-489');
insert into tag (id, name, slug) values (6, 'in blandit', 'tag-ffp-094');
insert into tag (id, name, slug) values (7, 'dui ', 'tag-hob-529');
insert into tag (id, name, slug) values (8, 'porta volutpat quam', 'tag-cto-238');
insert into tag (id, name, slug) values (9, 'integer a ', 'tag-yam-184');
insert into tag (id, name, slug) values (10, 'sed  sit amet cursus  integer aliquet', 'tag-lfy-696');
insert into tag (id, name, slug) values (11, 'eros  rutrum', 'tag-nwf-114');
insert into tag (id, name, slug) values (12, 'nec dui  in sagittis', 'tag-jew-785');
insert into tag (id, name, slug) values (13, 'vel nisl purus aliquet at', 'tag-iyv-769');
insert into tag (id, name, slug) values (14, 'quam pede pede', 'tag-osc-978');
insert into tag (id, name, slug) values (15, 'eleifend nibh', 'tag-vks-060');
insert into tag (id, name, slug) values (16, 'aliquet pulvinar sed nisl', 'tag-swo-198');
insert into tag (id, name, slug) values (17, 'nulla ut erat id mauris', 'tag-evp-148');
insert into tag (id, name, slug) values (18, 'vivamus in felis', 'tag-zcn-802');
insert into tag (id, name, slug) values (19, 'in felis eu sapien', 'tag-cja-654');
insert into tag (id, name, slug) values (20, 'justo sollicitudin ut suscipit', 'tag-ckn-068');
insert into tag (id, name, slug) values (21, 'elementum ligula', 'tag-yfx-555');
insert into tag (id, name, slug) values (22, 'et ultrices posuere cubilia curae', 'tag-ofu-872');
insert into tag (id, name, slug) values (23, 'ornare ut volutpat sapien', 'tag-mpb-162');
insert into tag (id, name, slug) values (24, 'et tempus semper est quam', 'tag-ssq-913');
insert into tag (id, name, slug) values (25, 'montes nascetur', 'tag-szb-657');
insert into tag (id, name, slug) values (26, 'augue vestibulum ante', 'tag-mcq-596');
insert into tag (id, name, slug) values (27, 'feugiat', 'tag-kmv-125');
insert into tag (id, name, slug) values (28, 'in tempus sit amet sem fusce consequat nulla nisl', 'tag-dxt-408');
insert into tag (id, name, slug) values (29, 'sollicitudin ut suscipit a feugiat et eros', 'tag-ouv-084');
insert into tag (id, name, slug) values (30, 'lacus at turpis', 'tag-lan-475');
insert into tag (id, name, slug) values (31, 'luctus sagittis', 'tag-aoo-800');
insert into tag (id, name, slug) values (32, 'molestie sed justo pellentesque viverra cras', 'tag-xet-170');
insert into tag (id, name, slug) values (33, 'diam vitae  nullam', 'tag-ydx-654');
insert into tag (id, name, slug) values (34, 'justo lacinia eget tincidunt eget', 'tag-pvw-409');
insert into tag (id, name, slug) values (35, 'nec  lacus', 'tag-qed-696');
insert into tag (id, name, slug) values (36, 'mauris ullamcorper rutrum', 'tag-ktg-497');
insert into tag (id, name, slug) values (37, 'faucibus orci luctus et', 'tag-pck-365');
insert into tag (id, name, slug) values (38, 'in congue in', 'tag-pob-458');
insert into tag (id, name, slug) values (39, 'porttitor lacus at', 'tag-vxm-249');
insert into tag (id, name, slug) values (40, 'nisi vulputate nonummy maecenas', 'tag-std-621');
insert into tag (id, name, slug) values (41, 'sapien iaculis congue vivamus', 'tag-put-588');
insert into tag (id, name, slug) values (42, 'scelerisque nec', 'tag-ozz-118');
insert into tag (id, name, slug) values (43, 'ipsum primis in', 'tag-uvf-480');
insert into tag (id, name, slug) values (44, 'lectus vestibulum', 'tag-cxp-761');
insert into tag (id, name, slug) values (45, 'nascetur ridiculus mus etiam vel', 'tag-gwz-180');
insert into tag (id, name, slug) values (46, 'maecenas leo odio condimentum id', 'tag-glc-700');
insert into tag (id, name, slug) values (47, 'sapien varius ut blandit non', 'tag-dvg-619');
insert into tag (id, name, slug) values (48, 'aliquam', 'tag-onp-755');
insert into tag (id, name, slug) values (49, 'nisl duis bibendum', 'tag-fsh-911');
insert into tag (id, name, slug) values (50, 'augue vel', 'tag-ucx-706');
insert into tag (id, name, slug) values (51, 'aliquet', 'tag-psa-472');
insert into tag (id, name, slug) values (52, 'varius vitae', 'tag-aoy-416');
insert into tag (id, name, slug) values (53, 'fusce lacus purus aliquet at feugiat non pretium', 'tag-dro-395');
insert into tag (id, name, slug) values (54, 'consectetuer eget rutrum at lorem', 'tag-okl-535');
insert into tag (id, name, slug) values (55, 'aliquet ultrices erat tortor sollicitudin mi', 'tag-icw-554');
insert into tag (id, name, slug) values (56, 'fusce congue diam id ornare', 'tag-gxj-330');
insert into tag (id, name, slug) values (57, 'sit amet sapien', 'tag-jbv-377');
insert into tag (id, name, slug) values (58, 'proin sapien', 'tag-mvk-951');
insert into tag (id, name, slug) values (59, 'nestle ', 'tag-kwb-422');
insert into tag (id, name, slug) values (60, 'vestibulum ante orci', 'tag-eii-056');
insert into tag (id, name, slug) values (61, 'volutpat dui maecenas tristique est et tempus semper', 'tag-fgy-089');
insert into tag (id, name, slug) values (62, 'nibh in lectus pellentesque', 'tag-fll-992');
insert into tag (id, name, slug) values (63, 'sociis natoque penatibus et', 'tag-sfw-286');
insert into tag (id, name, slug) values (64, 'libero', 'tag-wdc-041');
insert into tag (id, name, slug) values (65, 'dolor sit amet', 'tag-ucg-256');
insert into tag (id, name, slug) values (66, 'purus  sapien a libero', 'tag-byq-146');
insert into tag (id, name, slug) values (67, 'morbi non lectus aliquam sit amet', 'tag-ftt-095');
insert into tag (id, name, slug) values (68, 'sagittis dui vel nisl duis ac nibh', 'tag-nzp-330');
insert into tag (id, name, slug) values (69, 'id pretium iaculis', 'tag-lyd-799');
insert into tag (id, name, slug) values (70, 'curae donec pharetra magna vestibulum aliquet', 'tag-atp-868');
insert into tag (id, name, slug) values (71, 'in venenatis', 'tag-abh-267');
insert into tag (id, name, slug) values (72, 'erat nulla tempus vivamus in', 'tag-cqu-167');
insert into tag (id, name, slug) values (73, 'nec nisi lacus at velit vivamus', 'tag-utj-853');
insert into tag (id, name, slug) values (74, 'eu orci ', 'tag-mmg-397');
insert into tag (id, name, slug) values (75, 'sit', 'tag-avw-407');
insert into tag (id, name, slug) values (76, 'lorem integer tincidunt ante vel ipsum praesent', 'tag-vvy-322');
insert into tag (id, name, slug) values (77, 'odio', 'tag-bmd-351');
insert into tag (id, name, slug) values (78, 'phasellus insapien', 'tag-ikl-349');
insert into tag (id, name, slug) values (79, 'habitasse platea', 'tag-omi-815');
insert into tag (id, name, slug) values (80, 'ultrices aliquet maecenas leo odio', 'tag-lkx-635');
insert into tag (id, name, slug) values (81, 'imperdiet nullam sed', 'tag-izq-563');
insert into tag (id, name, slug) values (82, 'vel quis', 'tag-vxh-897');
insert into tag (id, name, slug) values (83, 'etiam  dictumst etiam', 'tag-wkx-045');
insert into tag (id, name, slug) values (84, 'duis  consequat', 'tag-ftx-514');
insert into tag (id, name, slug) values (85, 'neque vestibulum eget vulputate ut ultrices vel augue', 'tag-jia-753');
insert into tag (id, name, slug) values (86, 'eu massa donec', 'tag-pga-193');
insert into tag (id, name, slug) values (87, 'natoque', 'tag-lak-937');
insert into tag (id, name, slug) values (88, 'sodales', 'tag-stw-918');
insert into tag (id, name, slug) values (89, 'eget tempus vel pede', 'tag-mje-293');
insert into tag (id, name, slug) values (90, 'ac diam tristique est et', 'tag-hnl-001');
insert into tag (id, name, slug) values (91, 'mollis molestie lorem quisque ut erat curabitur', 'tag-ibw-940');
insert into tag (id, name, slug) values (92, 'in purus eu cum sociis', 'tag-hsb-527');
insert into tag (id, name, slug) values (93, 'dolor morbi', 'tag-rvi-662');
insert into tag (id, name, slug) values (94, 'praesent blandit magna', 'tag-nbr-091');
insert into tag (id, name, slug) values (95, 'nisi volutpat eleifend', 'tag-pbk-805');
insert into tag (id, name, slug) values (96, 'sit risus praesent', 'tag-vts-622');
insert into tag (id, name, slug) values (97, 'convallis morbi odio odio elementum eu interdum eu', 'tag-tro-280');
insert into tag (id, name, slug) values (98, 'libero  molestie nibh in', 'tag-ral-007');
insert into tag (id, name, slug) values (99, 'ut tellus nulla', 'tag-kbf-425');
insert into tag (id, name, slug) values (100, 'gravida', 'tag-lpc-278');
