server:
  port: 8085

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
    show-sql: false
    hibernate:
      ddl-auto: create-drop
  sql:
    init:
      mode: always
      data-locations: classpath*:/db/*.sql, classpath*:/db/links/*.sql
  web:
    resources:
      static-locations: classpath:/frontend/
  thymeleaf:
    prefix: classpath:/frontend/
  liquibase:
    enabled: false
    change-log: classpath:/db/changelog/changelog-master.yml
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  messages:
    basename: lang.messages

path:
  upload: d:/files/book-covers
  download: d:/files/book-files