server:
  port: 8085
  servlet:
    session:
      tracking-modes: cookie

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  web:
    resources:
      static-locations: classpath:/frontend/
  thymeleaf:
    prefix: classpath:/frontend/
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog-master.yml
    drop-first: false
    default-schema: public
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  messages:
    basename: lang.messages
  security:
    oauth2:
      client:
        registration:
          facebook:
            client-id: ${facebook_id}
            client-secret: ${facebook_secret}
            client-authentication-method: basic
            scope:
              - email
              - public_profile
  mail:
    host: smtp.yandex.ru
    port: 465
    username: ${email_username}
    password: ${email_password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
        debug: false
#  application:
#    name: bookshop
#  boot:
#    admin:
#      client:
#        url: http://localhost:8080
#        instance:
#          service-url: http://localhost:8085
#          health-url: http://localhost:8085/actuator/health
#          management-url: http://localhost:8085/actuator
#        enabled: true

#management:
#  endpoint:
#    health:
#      show-details: always
#  endpoints:
#    web:
#      exposure:
#        include: '*'


path:
  upload: d:/files/book-covers
  download: d:/files/book-files

auth:
  secret: kainart
  expiration: 3600000

twilio:
  ACCOUNT_SID: ${twilio_account_sid}
  AUTH_TOKEN: ${twilio_auth_token}
  TWILIO_NUMBER: ${twilio_phone_number}

mail:
  ADDRESS: adzmit@yandex.by

google:
  books:
    api:
      KEY: ${google_books_api_key}

yookassa:
  shop:
    ID: ${yookassa_id}
    KEY: ${yookassa_key}