server:
  port: 8085

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  web:
    resources:
      static-locations: classpath:/frontend/
  thymeleaf:
    prefix: classpath:/frontend/
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog-master.yml
    drop-first: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: validate
  mvc:
    path-match:
      matching-strategy: ant_path_matcher
  messages:
    basename: lang.messages

path:
  upload: d:/files/book-covers
  download: d:/files/book-files