insert into genre (id, name, parent_id, slug) values (1, 'Fiction', null, 'genre-syr-842');
insert into genre (id, name, parent_id, slug) values (2, 'Nonfiction', null, 'genre-vsf-086');
insert into genre (id, name, parent_id, slug) values (3, 'Poetry', null, 'genre-zqf-671');
insert into genre (id, name, parent_id, slug) values (4, 'Drama', null, 'genre-jvz-481');
insert into genre (id, name, parent_id, slug) values (5, 'Comedy', 4, 'genre-vzz-588');
insert into genre (id, name, parent_id, slug) values (6, 'Tragedy', 4, 'genre-aux-854');
insert into genre (id, name, parent_id, slug) values (7, 'Fantasy', 1, 'genre-wlv-703');
insert into genre (id, name, parent_id, slug) values (8, 'Traditional', 1, 'genre-sxa-518');
insert into genre (id, name, parent_id, slug) values (9, 'Historical', 1, 'genre-ioo-195');
insert into genre (id, name, parent_id, slug) values (10, 'Mystery', 1, 'genre-nbv-421');
insert into genre (id, name, parent_id, slug) values (11, 'Realistic Fiction', 1, 'genre-bdc-875');
insert into genre (id, name, parent_id, slug) values (12, 'Science Fiction', 1, 'genre-acf-071');
insert into genre (id, name, parent_id, slug) values (13, 'Romance', 1, 'genre-oaf-452');
insert into genre (id, name, parent_id, slug) values (14, 'Thriller', 1, 'genre-mar-783');
insert into genre (id, name, parent_id, slug) values (15, 'Biography', 2, 'genre-wyj-390');
insert into genre (id, name, parent_id, slug) values (16, 'Autobiography', 2, 'genre-myh-594');
insert into genre (id, name, parent_id, slug) values (17, 'Narrative', 2, 'genre-jwf-544');
insert into genre (id, name, parent_id, slug) values (18, 'Periodicals', 2, 'genre-gwm-495');
insert into genre (id, name, parent_id, slug) values (19, 'Reference', 2, 'genre-gwy-027');
insert into genre (id, name, parent_id, slug) values (20, 'Lyric', 3, 'genre-xic-301');
insert into genre (id, name, parent_id, slug) values (21, 'Narrative', 3, 'genre-ljq-890');
insert into genre (id, name, parent_id, slug) values (22, 'Dramatic', 3, 'genre-eun-497');
insert into genre (id, name, parent_id, slug) values (23, 'Mystery', 11, 'genre-yvk-455');
insert into genre (id, name, parent_id, slug) values (24, 'Myth', 8, 'genre-zgg-650');
insert into genre (id, name, parent_id, slug) values (25, 'Legend', 8, 'genre-zzc-207');
insert into genre (id, name, parent_id, slug) values (26, 'Folktale', 8, 'genre-zeb-204');
insert into genre (id, name, parent_id, slug) values (27, 'Tall Tale', 8, 'genre-pgi-957');
insert into genre (id, name, parent_id, slug) values (28, 'Fairy Tale', 8, 'genre-zos-205');
insert into genre (id, name, parent_id, slug) values (29, 'Fable', 8, 'genre-wgm-204');
insert into genre (id, name, parent_id, slug) values (30, 'Memoir', 16, 'genre-lux-719');