package com.example.MyBookShopApp.data.struct.author;

import com.example.MyBookShopApp.data.struct.book.BookEntity;
import com.example.MyBookShopApp.data.struct.book.links.Book2AuthorEntity;
import com.fasterxml.jackson.annotation.JsonIgnore;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;

import javax.persistence.*;
import java.util.ArrayList;
import java.util.List;

@Data
@Entity
@Table(name = "author")
@ApiModel(description = "data model of author entity")
public class AuthorEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @ApiModelProperty(value = "author id generated by db", position = 1)
    private Integer id;

    @Column(columnDefinition = "TEXT")
    private String description;

    @Column(name = "first_name", columnDefinition = "VARCHAR(255) NOT NULL")
    @ApiModelProperty(value = "first name of author", example = "Bob", position = 2)
    private String firstName;

    @Column(name = "last_name", columnDefinition = "VARCHAR(255) NOT NULL")
    @ApiModelProperty(value = "last name of author", example = "Hackintosh", position = 3)
    private String lastName;

    @ApiModelProperty(value = "photo of author", position = 4)
    private String photo;

    @ApiModelProperty(value = "mnemonic code of author" , position = 5)
    private String slug;

    @OneToMany(mappedBy = "author", cascade = CascadeType.ALL, orphanRemoval = true)
    private List<Book2AuthorEntity> author2books = new ArrayList<>();

    @Override
    public String toString() {
        return lastName + " " + firstName;
    }
}
